apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-pg-cluster # 클러스터의 이름
spec:
  instances: 4 # Primary 1개, Standby 2개 (총 3개 인스턴스)
  primaryUpdateStrategy : unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:15 # 사용할 PostgreSQL Docker 이미지 (PostgreSQL 13 이상 사용 권장)

  storage: # 각 PostgreSQL 인스턴스에 할당될 스토리지 설정
    size: 3Gi # 스토리지 크기
    storageClass: nfs-sc
    #  resizeInUseVolumes: False
  walStorage:
    size: 1Gi
    storageClass: nfs-sc

    #  externalVolumes:
    #- name: postgresql-wal-volume
    #  pvc:
    #    name: my-pg-wal-pvc
    #  mountPath: /var/lib/postgresql/pg_wal
    #- name: postgresql-log-volume
    #  pvc:
    #    name: my-pg-log-pvc
    #  mountPath: /var/log/postgresql

  postgresql:
    parameters:
      log_statement: 'ddl'
      log_min_duration_statement: '100ms'
      log_min_messages: 'log'
      log_line_prefix: '%m [%p] %q%u@%d '

  monitoring:
    enablePodMonitor: true

